### ISSUE TITLE
validate without error when i using invalidated keys

### ISSUE THREAD

**Issue by WestEnlarged** [getkin/kin-openapi#562] opened 2022-06-30 08:47 UTC
i'm not sure someone point this, or maybe need someting.

i add some error key in my spec, like this:

```
openapi: 3.0.0
info:
  version: 3.0.0
  description: test desc
  license:
    name: test
  title: test title
  errorkey: "abc"
paths:
  /hello:
    get:
      description: hello world.
      operationId: hello
      x-apisix-service_id: service1
      responses:
        '200':
          description: list response
        default:
          description: unexpected error
```

and get expected error when i put this spec on Swagger Editor 
![image](https://user-images.githubusercontent.com/28502860/176632988-8e2f1352-c331-4ada-ab9d-83c90b5b02d3.png)

But, when i execute my test like this, no error return. 
```
bytes := ReadFile(t, "myspec.yaml")
	loader := openapi3.NewLoader()
	openapi, err := loader.LoadFromData(bytes)
	assert.NoError(t, err)
	err = openapi.Validate(loader.Context)
	assert.NoError(t, err)
```

Maybe it's a bug or a feature request? 

----------
and request body on get , show get error but passed.
![image](https://user-images.githubusercontent.com/28502860/176643982-a64aa9d5-c02c-4020-8aa6-a82a3c46b83c.png)

**Comment by fenollp** [comment] 2022-07-29 15:43
Hi!
Thanks for reporting, indeed you've found another instance of #513 
Good news! I have a few leads that should fix this https://github.com/getkin/kin-openapi/compare/master...fenollp:kin-openapi:issue513 but this should take some more time.

**Comment by AnatolyRugalev** [comment] 2024-07-03 23:40
Duplicate of #513

**Closed** 2024-07-04 07:36 UTC
