### ISSUE TITLE
Response validation: validate headers

### ISSUE THREAD

**Issue by jamietanna** [getkin/kin-openapi#546] opened 2022-05-22 07:58 UTC
I've noticed while using the response validation filter for OpenAPI 3.x that header validation isn't performed.

As they can be marked as `required` we should validate them too.

**Comment by fenollp** [comment] 2022-07-29 15:51
Closing as duplicate of https://github.com/getkin/kin-openapi/issues/201
Please try implementing this, I'll happily review your code :)

**Closed by fenollp** 2022-07-29 15:51 UTC

**Comment by fenollp** [comment] 2022-10-28 14:03
@jamietanna see https://github.com/getkin/kin-openapi/pull/650
