### ISSUE TITLE
Upgrade from `v0.121.0` to `v0.122.0` Introduces loss of `T.Paths` when marshalling to yaml

### ISSUE THREAD

**Issue by mcblair** [getkin/kin-openapi#883] opened 2023-12-07 20:03 UTC
Details here: https://github.com/getkin/kin-openapi/pull/763#issuecomment-1846026849

**Comment by fenollp** [comment] 2023-12-08 12:24
Hey I'm having trouble understanding your issue. Could you tweak https://github.com/getkin/kin-openapi/pull/887 to show the bug please? Comment on it or make a PR to it...

**Comment by mcblair** [comment] 2023-12-08 19:10
Checking out `v0.121.0` of `kin-openapi` and running those tests yields all 3 passing.

**Comment by fenollp** [comment] 2023-12-11 11:01
I see. The thing is `yaml` v2/v3 packages don't seem to use `MarshalYAML` => https://pkg.go.dev/gopkg.in/yaml.v3#Marshal

This can indeed be seen as a regression: by introducing private fields (maps in `Paths`, `Callbacks`, `Responses`) 
> Struct fields are only marshalled if they are exported

Changing to https://github.com/invopop/yaml fixes this, while still depending on `yaml.v3`.
Is this closure enough for you? Or is it impossible in your context to make the switch?

**Comment by mcblair** [comment] 2023-12-29 17:17
> I see. The thing is `yaml` v2/v3 packages don't seem to use `MarshalYAML` => https://pkg.go.dev/gopkg.in/yaml.v3#Marshal
> 
> This can indeed be seen as a regression: by introducing private fields (maps in `Paths`, `Callbacks`, `Responses`)
> 
> > Struct fields are only marshalled if they are exported
> 
> Changing to https://github.com/invopop/yaml fixes this, while still depending on `yaml.v3`. Is this closure enough for you? Or is it impossible in your context to make the switch?

Apologies for the delay, spent a few weeks in the Philippines for the holidays 🇵🇭 

We decided to switch entirely to `invopop/yaml` but then stumbled upon a new issue: https://github.com/invopop/yaml/issues/12#issuecomment-1872228032. 

Kind of crazy: go with canonical go YAML and the billion-dollar mistake… or go with invopop YAML which flips some behaviors upside down, silently.

**Comment by sonu27** [comment] 2024-02-02 15:08
Could `m map[string]*PathItem` be made public?

**Comment by sonu27** [comment] 2024-02-02 15:41
Having the same issue, had to update my open API merger after PathItems were made private, but now paths are empty.

```go
package main

import (
	"fmt"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/rs/zerolog/log"
	"gopkg.in/yaml.v3"
	"os"
	"path/filepath"
)

func main() {
	base := openapi3.T{
		OpenAPI: "3.0.3",
		Info: &openapi3.Info{
			Title:   "Alfred API",
			Version: "1.0",
		},
		Servers: openapi3.Servers{
			&openapi3.Server{
				Description: "Current",
				URL:         "",
			},
		},
		Paths: &openapi3.Paths{},
		Components: &openapi3.Components{
			Schemas: openapi3.Schemas{},
		},
	}

	err := generate(&base, "./openapi.yaml")
	if err != nil {
		log.Fatal().Err(err).Msg("generating openapi spec")
	}
}

func generate(base *openapi3.T, path string) error {
	files, err := filepath.Glob("./svc/api-*/openapi.yaml")
	if err != nil {
		return fmt.Errorf("finding files: %w", err)
	}

	loader := openapi3.NewLoader()

	for _, file := range files {
		fmt.Printf("processing file: %s\n", file)
		doc, err := loader.LoadFromFile(file)
		if err != nil {
			return fmt.Errorf("loading file: %w", err)
		}

		// loop through paths and add to base, checking for duplicates
		for key, pathItem := range doc.Paths.Map() {
			if base.Paths.Find(key) != nil {
				return fmt.Errorf("duplicate path found: %s", key)
			}
			base.Paths.Set(key, pathItem)
		}

		// loop through schemas and add to base, checking for duplicates
		for name, schema := range doc.Components.Schemas {
			if _, ok := base.Components.Schemas[name]; ok {
				return fmt.Errorf("duplicate schema found: %s", name)
			}
			base.Components.Schemas[name] = schema
		}
	}

	b, err := yaml.Marshal(&base)
	if err != nil {
		return fmt.Errorf("marshalling base: %w", err)
	}

	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("file not created: %w", err)
	}

	_, err = f.Write(b)
	if err != nil {
		return fmt.Errorf("writing file: %w", err)
	}
	fmt.Printf("file created: %s\n", path)

	return nil
}
```

**Comment by fenollp** [comment] 2024-02-03 10:17
Please @sonu27 use the YAML lib this lib uses: `invopop`'s.

I'm closing this issue and suggest https://github.com/getkin/kin-openapi/issues/849 to discuss a different yaml lib.

This current issue is resolved: https://github.com/getkin/kin-openapi/issues/883#issuecomment-1872229182

**Closed by fenollp** 2024-02-03 10:17 UTC
Labels: bug

**Comment by sonu27** [comment] 2024-02-03 10:18
That library has its own issues (see above)

**Comment by fenollp** [comment] 2024-02-03 10:25
Does it? It ser/de YAML based on JSON tags, as intended.

**Comment by sonu27** [comment] 2024-02-05 09:12
Ah fair enough :)
Will switch to it
