### ISSUE TITLE
Attributes not listed in json schema are not giving errors during validation of json data

### ISSUE THREAD

**Issue by joshi-mohit** [getkin/kin-openapi#361] opened 2021-05-19 17:48 UTC
additionalProperties: "false" is one of the ways of resolving this, but there is an issue around this 
https://github.com/getkin/kin-openapi/issues/82

Is there any way or branch pull which has this fix either via additionalProperties or a code fix

**Comment by fenollp** [comment] 2021-05-31 06:49
You are right, `additionalProperties: false` is one way of fixing this and support is lacking right now.

You can track progress on https://github.com/getkin/kin-openapi/pull/318 for the fix (that'll come eventually).

**Comment by AnatolyRugalev** [comment] 2024-07-03 23:34
Duplicate of #82

**Closed** 2024-07-04 07:36 UTC
